highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
#paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
#url: http://biomadeira.github.io/vitae
#author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
# baseurl: /vitae/
title: Curriculum vitae
name: Ezequiel J. Zimmel
fecha: 15 nov 1987
email: ezequielzimmel@gmail.com
#email_full: mailto:youremail@me.com
#website: github.io/ezequielzimmel
#website_full: https://biomadeira.github.io/sustain
github: zimmcl
facebook: zimmcl
#twitter: twitter
tel: 3576-466529
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: J. Baigorri 422 1B
#postcode: EH3 5BL
city: Córdoba
country: Argentina
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
