highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
#paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
# baseurl: /vitae/
title: Ezequiel J. Zimmel - CV
name: Ezequiel J. Zimmel
fecha: 15 nov 1987
email: ezequielzimmel@gmail.com
#email_full: mailto:youremail@me.com
#website: zimmcl.github.io
#website_full: https://
github: zimmcl
facebook: zimmcl
linkedin: ezequiel-j-zimmel
#twitter: twitter
tel: 3576-466529
tel_full: 3576466529
google_maps: 'https://www.google.com.ar/maps/place/José+Baigorri+422,+X5001AJJ+Córdoba/'
address: J. Baigorri 422 1B
#postcode: xxxx-xxxx
city: Córdoba
country: Argentina
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
